@baseUrl = http://localhost:3001
@token = {{token}}

### Ruta de prueba
GET {{baseUrl}}/api/ping

### Registro de usuario
POST {{baseUrl}}/api/auth/register
Content-Type: application/json

{
  "email": "test2@correo.com",
  "password": "123456"
}

### Login de usuario
POST {{baseUrl}}/api/auth/login
Content-Type: application/json

{
  "email": "test2@correo.com",
  "password": "123456"
}

### Obtener todos los alumnos (requiere token)
GET {{baseUrl}}/api/alumnos
Authorization: Bearer {{t  "token": "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MTQsImVtYWlsIjoidGVzdDJAY29ycmVvLmNvbSIsImlhdCI6MTc2MzA4MDI5NiwiZXhwIjoxNzYzMDk0Njk2fQ.ovY8YI33fX8whM_4VKnTzIncZ9uiKL_URtXZN44ueTc"}}

### Crear alumno (requiere token)
POST {{baseUrl}}/api/alumnos
Content-Type: application/json
Authorization: Bearer {{token}}

{
  "nombre": "Juan",
  "apellido": "Pérez"
}

### Obtener todas las materias (requiere token)
GET {{baseUrl}}/api/materias
Authorization: Bearer {{token}}

### Obtener todas las notas (requiere token)
GET {{baseUrl}}/api/notas
Authorization: Bearer {{token}}
